### ISSUE TITLE
Upgrade Serverless Framework

### ISSUE THREAD

**Issue by BrandonE** [pumasecurity/serverless-prey#21]
The versions we are using are quite outdated.

**Comment by BrandonE** [comment]
Just upgraded Serverless to `1.83.0` for both Panther and Cheetah, preventing this error in Panther:

```bash
Serverless: Uploading artifacts...
Serverless: Uploading service panther.zip file to S3 (1.58 KB)...
  Error --------------------------------------------------
  Error: Unknown object type "asyncfunction"
      at Object._object (/home/student/code/serverless-prey/panther/node_modules/object-hash/index.js:218:17)
      at Object._function (/home/student/code/serverless-prey/panther/node_modules/object-hash/index.js:319:14)
      at Object.dispatch (/home/student/code/serverless-prey/panther/node_modules/object-hash/index.js:185:30)
```

I also used a random identifier for Cheetah project name to avoid collisions, which fixes [this issue](https://github.com/serverless/serverless/issues/6820).

We can consider upgrading to Serverless v2, but this is not as urgent now that this error is dealt with.

**Comment by ejohn20** [comment]
No longer needed. Serverless has been removed to avoid node dependency hell.
